# TrendVoyage - configuration for the working Google Trends + Spark pipeline

# RapidAPI - Skyscanner
RAPIDAPI_KEY = "YOUR_RAPIDAPI_KEY"

# OpenWeatherMap
OPENWEATHER_API_KEY = "YOUR_OPENWEATHER_KEY"

# Google Trends
GTRENDS_TIMEFRAME = "today 3-m"
GTRENDS_GEO = "IN"
GTRENDS_FASHION_KW = [
    "ethnic wear",
    "streetwear India",
    "summer fashion 2025",
    "boho style",
    "minimalist outfit",
    "kurta set trending",
    "coquette aesthetic",
    "cargo pants outfit",
    "linen shirt women",
    "oversized blazer outfit",
    "old money style",
    "capsule wardrobe",
    "quiet luxury fashion",
    "y2k fashion",
    "airport outfit women",
    "festive saree trends",
    "indo western dress",
    "maxi dress outfit",
    "denim on denim",
    "wedding guest outfit India",
    "travel outfit women",
    "monsoon fashion",
    "gen z fashion trends",
    "office wear women",
]
GTRENDS_TRAVEL_KW = [
    "Goa trip",
    "Manali travel",
    "Bali budget trip",
    "Jaipur travel",
    "Kerala trip",
    "Udaipur trip",
    "Kashmir travel",
    "Rishikesh trip",
    "Pondicherry travel",
    "Munnar trip",
    "Ooty travel",
    "Agra travel",
    "Taj Mahal trip",
    "Varanasi travel",
    "Amritsar trip",
    "Jaisalmer travel",
    "Hampi trip",
    "Mysore travel",
    "Darjeeling trip",
    "Shimla travel",
    "Ladakh trip",
    "Andaman trip",
    "Coorg travel",
    "Khajuraho trip",
    "Ajanta Ellora trip",
    "Mahabalipuram travel",
    "Konark Sun Temple trip",
    "Madurai travel",
    "Kodaikanal trip",
    "Nainital travel",
    "Mussoorie trip",
    "Sikkim travel",
    "Meghalaya trip",
    "Alleppey travel",
    "Wayanad trip",
    "Ayodhya travel",
    "Mathura Vrindavan trip",
    "Rann of Kutch trip",
    "Statue of Unity travel",
    "Srinagar trip",
    "Auli travel",
    "Chikmagalur trip",
    "Mount Abu travel",
    "Bhubaneswar travel",
    "Puri trip",
    "Gokarna trip",
    "Mahabaleshwar trip",
    "Lonavala trip",
    "Tawang trip",
    "Kaziranga trip",
    "Jim Corbett trip",
    "Coimbatore travel",
    "Hyderabad trip",
    "Delhi weekend getaway",
    "Mumbai weekend trip",
    "Kedarnath trip",
    "Badrinath travel",
    "Leh Ladakh bike trip",
    "Spiti Valley trip",
    "Kasol travel",
    "Bir Billing trip",
    "Dharamshala travel",
    "Gangtok trip",
    "Ziro Valley travel",
    "Cherrapunji trip",
    "Lakshadweep trip",
    "Diu travel",
    "Kutch festival trip",
    "Jodhpur travel",
    "Pushkar trip",
    "Rameswaram travel",
    "Kanyakumari trip",
    "Mcleodganj trip",
    "Auroville travel",
    "Shillong trip",
]

GTRENDS_TRAVEL_LABELS = {
    "Goa trip": "Goa",
    "Manali travel": "Manali",
    "Bali budget trip": "Bali",
    "Jaipur travel": "Jaipur",
    "Kerala trip": "Kerala",
    "Udaipur trip": "Udaipur",
    "Kashmir travel": "Kashmir",
    "Rishikesh trip": "Rishikesh",
    "Pondicherry travel": "Pondicherry",
    "Munnar trip": "Munnar",
    "Ooty travel": "Ooty",
    "Agra travel": "Agra",
    "Taj Mahal trip": "Taj Mahal",
    "Varanasi travel": "Varanasi",
    "Amritsar trip": "Amritsar",
    "Jaisalmer travel": "Jaisalmer",
    "Hampi trip": "Hampi",
    "Mysore travel": "Mysore",
    "Darjeeling trip": "Darjeeling",
    "Shimla travel": "Shimla",
    "Ladakh trip": "Ladakh",
    "Andaman trip": "Andaman",
    "Coorg travel": "Coorg",
    "Khajuraho trip": "Khajuraho",
    "Ajanta Ellora trip": "Ajanta Ellora",
    "Mahabalipuram travel": "Mahabalipuram",
    "Konark Sun Temple trip": "Konark",
    "Madurai travel": "Madurai",
    "Kodaikanal trip": "Kodaikanal",
    "Nainital travel": "Nainital",
    "Mussoorie trip": "Mussoorie",
    "Sikkim travel": "Sikkim",
    "Meghalaya trip": "Meghalaya",
    "Alleppey travel": "Alleppey",
    "Wayanad trip": "Wayanad",
    "Ayodhya travel": "Ayodhya",
    "Mathura Vrindavan trip": "Mathura Vrindavan",
    "Rann of Kutch trip": "Rann of Kutch",
    "Statue of Unity travel": "Statue of Unity",
    "Srinagar trip": "Srinagar",
    "Auli travel": "Auli",
    "Chikmagalur trip": "Chikmagalur",
    "Mount Abu travel": "Mount Abu",
    "Bhubaneswar travel": "Bhubaneswar",
    "Puri trip": "Puri",
    "Gokarna trip": "Gokarna",
    "Mahabaleshwar trip": "Mahabaleshwar",
    "Lonavala trip": "Lonavala",
    "Tawang trip": "Tawang",
    "Kaziranga trip": "Kaziranga",
    "Jim Corbett trip": "Jim Corbett",
    "Coimbatore travel": "Coimbatore",
    "Hyderabad trip": "Hyderabad",
    "Delhi weekend getaway": "Delhi Getaway",
    "Mumbai weekend trip": "Mumbai Getaway",
    "Kedarnath trip": "Kedarnath",
    "Badrinath travel": "Badrinath",
    "Leh Ladakh bike trip": "Leh Ladakh",
    "Spiti Valley trip": "Spiti Valley",
    "Kasol travel": "Kasol",
    "Bir Billing trip": "Bir Billing",
    "Dharamshala travel": "Dharamshala",
    "Gangtok trip": "Gangtok",
    "Ziro Valley travel": "Ziro Valley",
    "Cherrapunji trip": "Cherrapunji",
    "Lakshadweep trip": "Lakshadweep",
    "Diu travel": "Diu",
    "Kutch festival trip": "Kutch Festival",
    "Jodhpur travel": "Jodhpur",
    "Pushkar trip": "Pushkar",
    "Rameswaram travel": "Rameswaram",
    "Kanyakumari trip": "Kanyakumari",
    "Mcleodganj trip": "Mcleodganj",
    "Auroville travel": "Auroville",
    "Shillong trip": "Shillong",
}

# App settings
APP_NAME = "TrendVoyage"
APP_VERSION = "1.0.0"
DEBUG = False
